#!/bin/bash
echo "=============== BUILD ==============="
# docker build --build-arg XYZ=$XYZ -f $DOCKERFILE_PATH -t $IMAGE_NAME .
ls -la
pwd
printenv
echo $XYZ
docker build --build-arg XYZ=$XYZ -t $IMAGE_NAME -f Dockerfile ../../
